### PR TITLE
Fix add calendar

### LINKED ISSUE #1029: Add google event link to acitivity page for admins and members
Whenever a board member makes a new activity, they must manually add this to the sticky calendar.
Add a small button that links to google calendar and fills in the form for an activity such as this with the relevant activity information:

https://www.google.com/calendar/render?action=TEMPLATE&text=Cool+he&details=Dit+kunnen+we+heel+makkelijk+inbouwen&location=Utrecht&dates=20221013T082600Z%2F20221013T131500Z

Probably also a nice feature to add this to the member activity page since not everybody uses the sticky calendar/

### PR DESCRIPTION
**Pull request by JustNireon**
resolves #1029

### CODE REVIEW

File: app/models/activity.rb [hunk 1]
```diff
@@ -356,6 +356,18 @@ def thumbnail_representation
     end
   end
 
+  def google_event
+    return nil if start.nil? || self.end.nil?
+
+    # check locale for correct description
+    description = if I18n.locale == :en
```
Comment (SanderHageman) [inline app/models/activity.rb:363]: We (the board) now add the activity URL to the description in the calendar; could you prepend that too?

**Review by SanderHageman — APPROVED** [review]
Small change, as a nice to have, otherwise a big help already!

**Review by SanderHageman — APPROVED** [review]
LGTM
