### PR TITLE
Fix payment buttons

### LINKED ISSUE #521: Payments button not working
### Expected behaviour
When clicking the button behind a member on the members page, the payment status switches.
The button changes too.

### Actual behavior
Nothing happens

### Steps to reproduce
- admin
- browser: any

### LINKED ISSUE #532: 'Inschrijven' and 'Uitschrijven' buttons not working
users cannot subscribe or unsubscribe to an activity

### PR DESCRIPTION
**Pull request by FInnvos123**
Fixes #521
Fixes #532 

The buttons update the payment status but there's no visual indication until the page is reloaded because all alerts in koala are currently broken.

Instead of trying to fix the creative custom alert function (see first commit), I'll be using [toastr-rails](https://github.com/tylergannon/toastr-rails)

### CODE REVIEW

File: app/assets/javascripts/admin/payments.js [hunk 1]
```diff
@@ -71,12 +71,10 @@ function getCheckoutTransactions (button) {
     // Bind json data to copy button
     $("#copy_transactions button").attr("data-clipboard-text", data);
 
-    data = JSON.parse(data);
-
```
Comment (Riscky) [inline app/assets/javascripts/admin/payments.js]: probably related to this: the 'copy checkout transactions' functionality is broken
